// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package cisco

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "cisco", asset.ModuleFieldsPri, AssetCisco); err != nil {
		panic(err)
	}
}

// AssetCisco returns asset data.
// This is the base64 encoded gzipped contents of module/cisco.
func AssetCisco() string {
	return "eJzEj00OwiAUhPecYtJ9L8DCnQfBMhpSKARolNubFn9q27gzfjveC9+badGzSHQmdV4A2WRLiWZ+NwKItFSJEidmJQDN1EUTsvGDxEEAqH/hvB4tBXA2tDrJedViUI5v/UQugRKX6MfwmOw4PzVLVSop073Ge76Jde4nu7cqG/M6wjIGb8qFue+SmqVnufqoV7svlyeOVViPblqPIRvHX7TemP/Y+h4AAP//DHinZw=="
}
